name: Exportables

on:
    create:
        tags:
            - semana*
            - test-semana*

jobs:

    buildAndUpload:

        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v1

            - name: Install dependencies
              env:
                  FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}
                  FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}

              run: |
                  npm install

            - name: Build exportables
              run: |
                  npm run exportables:build

            - name: Build exportables
              run: |
                  npm run exportables:upload --folder ${GITHUB_REF/refs\/tags\//}
